# Required: A short name for the action package
name: Robocorp Control Room

# Required: A description of what's in the action package.
description: Action package description

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

# Package version number, recommend using semver.org
version: 1.0.0

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.2.37
  - python-dotenv=1.0.1

  pypi:
  - sema4ai-actions=0.10.0
  - requests=2.32.3
  - pydantic=2.8.2

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip